import type { CSSProperties } from 'react'

// Montera Finance-inspired token system.
// Playful fintech aesthetic: light warm-gray page bg, white surface chips,
// vivid lime accent, deeply rounded corners (pill buttons, 30px cards).

export const editableRootStyle = {
  '--slot4-page-bg': '#f6f6f6',
  '--slot4-page-text': '#0c0c0c',
  '--slot4-panel-bg': '#ffffff',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#86868b',
  '--slot4-soft-muted-text': '#a1a1a6',
  '--slot4-accent': '#d0ff52',
  '--slot4-accent-fill': '#d0ff52',
  '--slot4-accent-soft': '#f2ffcc',
  '--slot4-on-accent': '#0c0c0c',
  '--slot4-dark-bg': '#0c0c0c',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#efefef',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#f0f0f0',
  '--slot4-lavender': '#e8e6ff',
  '--slot4-gray': '#ececec',
  '--slot4-mint': '#9ff2e0',
  '--slot4-pink': '#ffd0f5',
  '--slot4-orange': '#fd8c3b',
  '--slot4-blue': '#2670ff',
  '--slot4-lemon': '#d8ff70',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f6f6f6',
  '--editable-page-text': '#0c0c0c',
  '--editable-container': '1360px',
  '--editable-border': 'rgba(0,0,0,0.10)',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#0c0c0c',
  '--editable-nav-active': '#0c0c0c',
  '--editable-nav-active-text': '#d0ff52',
  '--editable-cta-bg': '#0c0c0c',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#0c0c0c',
  '--editable-footer-text': '#ffffff',
  '--slot4-radius-pill': '5rem',
  '--slot4-radius-card': '1.875rem',
  '--slot4-radius-soft': '1.5rem',
  '--slot4-radius-input': '1rem',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-page-text)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  mintBg: 'bg-[var(--slot4-mint)]',
  pinkBg: 'bg-[var(--slot4-pink)]',
  lemonBg: 'bg-[var(--slot4-lemon)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/12',
  shadow: 'shadow-[0_1px_2px_rgba(0,0,0,0.03)]',
  shadowStrong: 'shadow-[0_20px_60px_rgba(0,0,0,0.10)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(12,12,12,0.02),rgba(12,12,12,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-6 lg:px-10',
    sectionY: 'py-16 sm:py-20 lg:py-[6.25rem]',
    sectionYTight: 'py-10 sm:py-14 lg:py-16',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[320px]',
  },
  type: {
    eyebrow: 'editable-label text-[0.72rem] font-medium uppercase tracking-[0.15em]',
    heroTitle: 'editable-display text-[2.5rem] font-semibold leading-[1.02] tracking-[-0.0225em] sm:text-[4rem] lg:text-[4.75rem]',
    sectionTitle: 'editable-display text-[2.125rem] font-semibold leading-[1.05] tracking-[-0.0225em] sm:text-[2.75rem] lg:text-[3.5rem]',
    subTitle: 'editable-display text-[1.5rem] font-semibold leading-[1.1] tracking-[-0.02em] sm:text-[2rem] lg:text-[2.125rem]',
    body: 'text-[1rem] leading-[1.6] text-[var(--slot4-muted-text)]',
    bodyLg: 'text-[1.125rem] leading-[1.55] text-[var(--slot4-muted-text)] sm:text-[1.25rem]',
    emphasis: 'italic',
  },
  surface: {
    card: `rounded-[var(--slot4-radius-card)] ${editablePalette.surfaceBg} transition duration-500`,
    soft: `rounded-[var(--slot4-radius-card)] ${editablePalette.warmBg}`,
    dark: `rounded-[var(--slot4-radius-card)] ${editablePalette.darkBg} ${editablePalette.darkText}`,
    lime: `rounded-[var(--slot4-radius-card)] bg-[var(--slot4-accent)] text-[var(--slot4-on-accent)]`,
    mint: `rounded-[var(--slot4-radius-card)] bg-[var(--slot4-mint)] text-[var(--slot4-page-text)]`,
    pink: `rounded-[var(--slot4-radius-card)] bg-[var(--slot4-pink)] text-[var(--slot4-page-text)]`,
  },
  badge: {
    pill: `inline-flex items-center gap-2 rounded-full border ${editablePalette.border} bg-[var(--slot4-surface-bg)] px-3.5 py-1.5 text-[0.72rem] font-medium uppercase tracking-[0.14em] text-[var(--slot4-page-text)]`,
    accentPill: `inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent)] px-3.5 py-1.5 text-[0.72rem] font-medium uppercase tracking-[0.14em] text-[var(--slot4-on-accent)]`,
    darkPill: `inline-flex items-center gap-2 rounded-full bg-[var(--slot4-dark-bg)] px-3.5 py-1.5 text-[0.72rem] font-medium uppercase tracking-[0.14em] text-[var(--slot4-dark-text)]`,
    ghost: `inline-flex items-center gap-2 rounded-full border ${editablePalette.border} px-3 py-1 text-[0.72rem] font-medium uppercase tracking-[0.12em] text-[var(--slot4-muted-text)]`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-dark-bg)] px-7 py-3.5 text-[0.9rem] font-medium tracking-[-0.005em] text-[var(--slot4-dark-text)] transition duration-300 hover:bg-[var(--slot4-accent)] hover:text-[var(--slot4-on-accent)] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-transparent px-7 py-3.5 text-[0.9rem] font-medium tracking-[-0.005em] text-[var(--slot4-page-text)] transition duration-300 hover:bg-[var(--slot4-dark-bg)] hover:text-[var(--slot4-dark-text)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent)] px-7 py-3.5 text-[0.9rem] font-medium tracking-[-0.005em] text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[var(--slot4-dark-bg)] hover:text-[var(--slot4-dark-text)] active:scale-[0.98]`,
    ghost: `inline-flex items-center justify-center gap-2 rounded-full bg-transparent px-5 py-2.5 text-[0.9rem] font-medium text-[var(--slot4-page-text)] transition hover:bg-[var(--slot4-warm)]`,
    onDark: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent)] px-7 py-3.5 text-[0.9rem] font-medium tracking-[-0.005em] text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[var(--slot4-dark-text)] hover:text-[var(--slot4-dark-bg)]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[var(--slot4-radius-soft)] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[var(--slot4-radius-card)] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/3]',
    ratioTall: 'aspect-[3/4]',
    ratioWide: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_28px_60px_rgba(0,0,0,0.10)]',
    fade: 'transition duration-300 hover:opacity-85',
    zoom: 'transition duration-700 hover:scale-[1.03]',
  },
} as const

export const aiLayoutRules = [
  'Redesign starts by editing tokens in editableRootStyle; every component consumes them via CSS variables.',
  'Buttons are pill-shaped (rounded-full). Cards use --slot4-radius-card (1.875rem).',
  'Signature accent is neon lime (#d0ff52) — used sparingly, high-impact.',
  'Dark bands use --slot4-dark-bg (#0c0c0c) with lime numerals.',
  'Chip cards may swap surface bg for mint, pink, or lime.',
  'Section spacing follows section / sectionY / sectionYTight rhythms.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
